######################################################
## @author   Md. Emran Hossain <emranhos1@gmail.com> #
## @version  1.0.00 EH                               #
## @since    1.0.00 EH                               #
######################################################

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#PHPMyAdmin Config
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/transformation_portal?autoReconnect=true&useSSL=false
#    username: root
#    password:

##MySQL Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transformation_portal?autoReconnect=true&useSSL=false
    username: root
    password: root

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

# Hibernate ddl auto (create, create-drop, validate, update)
# For initital Data Please modify update to create-drop
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 909196181044-ng18pej66tc8qp31u22ifqsrbnth6t7a.apps.googleusercontent.com
            clientSecret: KyeTxFknWqrF67nrHnnuep7d
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 242172917528514
            clientSecret: a80858d529bb56d7c0af8d1d0477ee2f
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: 86ac58d9101d7ddd165b
            clientSecret: c20c4fa21837468f2f938b5fda29635a33c6ba0d
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
